### ISSUE TITLE
Add slevomat coding standard

### ISSUE THREAD

**Issue by n-peugnet** [codacy/codacy-codesniffer#27] opened 2019-06-17 10:20 UTC
Could it be possible to add the [Slevomat Coding Standard](https://github.com/slevomat/coding-standard#how-to-run-the-sniffs)'s rules to the available ruleset of PHP codesniffer ?
From the tool pattern list as well as from the configuration file.

I am currently using this standard trough a composer installation but this is of course not working in Codacy as it doesn't install the dependencies.

I thought that including it by default would be a good idea as it is a quite used standard and as this is what you did with angular plugin and eslint.

**Comment by lolgab** [comment] 2019-07-31 11:00
We are planning to update codacy-codesniffer to latest version ( 3.4.2 ). It should be the goal for the next 3 weeks.
During the update we will address the lack of `coding-standard` plugin you are requesting.

**Comment by bkdotcom** [comment] 2020-02-05 14:28
How do I go about using the slevomat sniffs with a custom phpcs.xml file??

My PHP Codesniffer log:

```
KubernetesDockerRunner: Container for codacy/codacy-codesniffer:1.3.1 exited with non-zero code 1
Error executing the tool
java.lang.Exception: 
CodeSniffer exited with code 3
stdout: ERROR: Referenced sniff "SlevomatCodingStandard.Arrays" does not exist

```

My phpcs.xml contains
```xml
    <config name="installed_paths" value="/Users/bkent/Dropbox/htdocs/common/vendor/bdk/PHPDebugConsole/vendor/slevomat/coding-standard"/>

    <rule ref="SlevomatCodingStandard.Arrays" />
```

**Comment by josemiguelmelo** [comment] 2020-02-06 14:59
Hi @bkdotcom 

On `phpcs.xml` you have the `installed_paths` configuration, which may be causing this issue because it may be trying to find the slevomat/coding-standard on the wrong folder. Do you really need it? This configuration should typically be set in the actual PHPCS config file, and not in a ruleset.

**Comment by bkdotcom** [comment] 2020-02-06 15:19
@josemiguelmelo 
I thought the rulset was the config file!
¯\\\_(ツ)_/¯
Using the `<config name="installed_paths" />` "option" per the [slevomat install instructions](https://github.com/slevomat/coding-standard/#installation)

Per my experience using phpcs locally, phpcs seems to ignore invalid paths defined in installed_paths..   There's also no logic to derive that "vendor/slevomat/coding-standard" maps to the sniff "SlevomatCodingStandard.Arrays"   (since it didn't scan the directory for sniffs).  So I don't think the invalid path is the root of the error.

There's an open [PHP Codesniffer Issue](https://github.com/squizlabs/PHP_CodeSniffer/issues/2776)  regarding how it's currently an pain-in-the-rump to set the installed_paths value...   it needs to be absolute, or relative to the current "working directory".   Relative to the phpcs.xml doesn't work..

Anyhow, that's all moot because Codacy doesn't run composer / install dependencies

**Comment by josemiguelmelo** [comment] 2020-02-10 15:58
The problem is that when installed_paths is defined on the phpcs.xml, it overrides the configuration provided by the command `phpcs --config-set installed_paths /path/to/one,/path/to/two`, even if the path is invalid. As consequence, the plugin will not be found.

**Comment by bkdotcom** [comment] 2020-02-10 17:59
Progress!
now I get 
```
CodeSniffer exited with code 3
stdout: ERROR: Referenced sniff "SlevomatCodingStandard.Classes.ClassStructure" does not exist
```

[ClassStructure Sniff was added with release 6.1.0](https://github.com/slevomat/coding-standard/releases/tag/6.1.0)

**Comment by josemiguelmelo** [comment] 2020-02-11 11:07
Thank you for testing it. I opened another issue to update Slevomat CS to version 6.1.5. 
Let's see if it solves the problem.

**Comment by josemiguelmelo** [comment] 2020-02-14 15:28
Hello @bkdotcom,
Already updated Slevomat CS to version 6.1.5 so the issue should be fixed. Can you check if it is now solved?

**Comment by bkdotcom** [comment] 2020-02-14 16:14
@josemiguelmelo 
No issues now!  Commit log has happy green checkmark next to "PHP Code Sniffer"

Thanks

**Comment by josemiguelmelo** [comment] 2020-02-14 16:16
Happy it worked! 🎉😀
Thanks for reporting the error,
Jose

**Closed by josemiguelmelo** 2020-02-14 16:16 UTC
